### ISSUE TITLE
Gammu splits UTF-16 surrogate pairs in two in GSM_EncodeMultiPartSMS

### ISSUE THREAD

**Issue by browndav** [browndav/gammu-json#3]
Since `libgammu` uses UCS-2-BE internally, it's completely oblivious to UTF-16 surrogate pairs. When encoding a multi-part SMS, it'll happily split a message between a lead surrogate and trailing surrogate, causing the character to not display (in either message part) if for some reason the message cannot be reassembled (e.g. a carrier strips the UDH off, or the receiving software does not support reassembly).

We should split two bytes early if the last 16 bits in the message segment would have been between 0xd800 and 0xd2ff inclusive.

**Comment by muhammadbuchory** [comment]
hello, how to integrated gammu with nodejs code?
